security:
  # https://symfony.com/doc/current/security.html#registering-the-user-provider
  providers:
    users_in_memory: { memory: null }
    users:
      entity:
        class: App\Entity\User
        property: email
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      id: App\Security\UserProvider

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: auto

  # https://symfony.com/doc/current/security/authenticator_manager.html
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/login$
      security: false

    admin:
      pattern: ^/admin
      provider: users
      form_login:
        login_path: app_login
        check_path: app_login
        username_parameter: email
        password_parameter: password
      logout:
        path: app_logout
        target: home
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800 # 7 jours

    main:
      lazy: true
      provider: users
      form_login:
        login_path: app_login
        check_path: app_login
        username_parameter: email
        password_parameter: password
      logout:
        path: app_logout
        target: home

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/reserver, roles: PUBLIC_ACCESS }
    - { path: ^/reservation, roles: PUBLIC_ACCESS }
