<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260813204743 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, appointment_id INT DEFAULT NULL, text TEXT NOT NULL, category VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9474526CA76ED395 ON comment (user_id)');
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, telephone VARCHAR(20) NOT NULL, adresse VARCHAR(255) NOT NULL, ville VARCHAR(100) NOT NULL, code_postal VARCHAR(10) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE intervention (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_intervention TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, heure_intervention TIME(0) WITHOUT TIME ZONE NOT NULL, technicien VARCHAR(255) DEFAULT NULL, commentaire TEXT DEFAULT NULL, prix_realise DOUBLE PRECISION DEFAULT NULL, date_realisation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, heure_realisation TIME(0) WITHOUT TIME ZONE DEFAULT NULL, photos TEXT DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reservation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D11814ABB83297E7 ON intervention (reservation_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, message TEXT NOT NULL, type VARCHAR(50) NOT NULL, lue BOOLEAN NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reservation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAB83297E7 ON notification (reservation_id)');
        $this->addSql('CREATE TABLE point (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, source VARCHAR(50) NOT NULL, devis_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B7A5F324A76ED395 ON point (user_id)');
        $this->addSql('CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero VARCHAR(255) NOT NULL, type_prestation VARCHAR(255) NOT NULL, nombre_panneaux INT NOT NULL, date_souhaitee TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, heure_souhaitee TIME(0) WITHOUT TIME ZONE NOT NULL, duree_estimee DOUBLE PRECISION NOT NULL, prix_estime DOUBLE PRECISION NOT NULL, commentaire_client TEXT DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(50) NOT NULL, customer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42C849559395C3F3 ON reservation (customer_id)');
        $this->addSql('CREATE TABLE reservation_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_action TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, heure_action TIME(0) WITHOUT TIME ZONE NOT NULL, administrateur VARCHAR(255) DEFAULT NULL, action VARCHAR(255) NOT NULL, ancienne_valeur TEXT DEFAULT NULL, nouvelle_valeur TEXT DEFAULT NULL, reservation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_402FCBCEB83297E7 ON reservation_history (reservation_id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE intervention ADD CONSTRAINT FK_D11814ABB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE point ADD CONSTRAINT FK_B7A5F324A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849559395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation_history ADD CONSTRAINT FK_402FCBCEB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE devis ADD user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE devis ADD CONSTRAINT FK_8B27C52BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8B27C52BA76ED395 ON devis (user_id)');
        $this->addSql('ALTER TABLE discount ADD CONSTRAINT FK_E1E0B40EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526CA76ED395');
        $this->addSql('ALTER TABLE intervention DROP CONSTRAINT FK_D11814ABB83297E7');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAB83297E7');
        $this->addSql('ALTER TABLE point DROP CONSTRAINT FK_B7A5F324A76ED395');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C849559395C3F3');
        $this->addSql('ALTER TABLE reservation_history DROP CONSTRAINT FK_402FCBCEB83297E7');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE intervention');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE point');
        $this->addSql('DROP TABLE reservation');
        $this->addSql('DROP TABLE reservation_history');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844A76ED395');
        $this->addSql('ALTER TABLE devis DROP CONSTRAINT FK_8B27C52BA76ED395');
        $this->addSql('DROP INDEX IDX_8B27C52BA76ED395');
        $this->addSql('ALTER TABLE devis DROP user_id');
        $this->addSql('ALTER TABLE discount DROP CONSTRAINT FK_E1E0B40EA76ED395');
    }
}
